services:
  - type: web
    name: ross-rent
    runtime: node
    plan: free
    buildCommand: cd backend && NODE_ENV=development npm install && npm run build && cd ../frontend && NODE_ENV=development npm install && npm run build
    startCommand: cd backend && node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: "20.18.1"
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: "10000"
      - key: USE_MOCK_DATA
        value: "true"
      - key: FRONTEND_ORIGIN
        value: "*"
